<?php
/**
 * Copyright © IURCO and PRISMA. All rights reserved.
 */

/**
 * @var \Prisma\Payway\Block\Form $block
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 * @var \Magento\Framework\Escaper $escaper
 */
?>
<fieldset class="admin__fieldset payment-method" id="payment_form_<?= $escaper->escapeHtml($block->getMethodCode()) ?>">
    <div class="admin__field _required">
        <label for="po_number" class="admin__field-label">
            <span><?= $escaper->escapeHtml(__('Information')) ?></span>
        </label>
        <div class="admin__field-control">
            <?= /* @noEscape */ $block->getInfoData('additional_information') ?>
        </div>
    </div>
</fieldset>
<?php
//    /* @noEscape */
//$secureRenderer->renderStyleAsTag(
//    "display:none",
//    'fieldset#payment_form_' . $block->escapeJs($block->getMethodCode())
//)
?>
